CREATE TABLE IF NOT EXISTS `logs` (
    `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
    `type` VARCHAR(50) NOT NULL,
    `message` TEXT NOT NULL,
    `summary` VARCHAR(255) NOT NULL,
    `context` TEXT NULL DEFAULT NULL,
    `post_data` TEXT NULL DEFAULT NULL,
    `get_data` TEXT NULL DEFAULT NULL,
    `ip` VARCHAR(100) NULL DEFAULT NULL,
    `hostname` VARCHAR(100) NULL DEFAULT NULL,
    `uri` TEXT NULL DEFAULT NULL,
    `refer` TEXT NULL DEFAULT NULL,
    `user_agent` TEXT NULL DEFAULT NULL,
    `user_id` INT(11) NULL DEFAULT NULL,
    `count` INT(10) NULL DEFAULT NULL,
    `created` DATETIME NULL DEFAULT NULL,
    PRIMARY KEY USING BTREE (`id`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 813
    DEFAULT CHARACTER SET = utf8
    ROW_FORMAT = DYNAMIC;
